# MongoDB Configuration
mongodb.host=localhost
mongodb.port=27017
mongodb.database=garantias_db
mongodb.username=rootuser
mongodb.password=RootPass123!
mongodb.auth.database=admin

# Odoo Configuration
odoo.url=http://localhost:8069
odoo.database=odoo_db
odoo.username=admin@empresa.com
odoo.password=admin